#pragma once
#include "core/DataTypes.h"

class Data {
public:
  REAL4_ARRAY POSITION_R;
  REAL4_ARRAY VELOCITY_MASS;
  REAL4_ARRAY ANGULAR_VELOCITY_MATERIAL;
  REAL4_ARRAY FORCE;
  REAL4_ARRAY TORQUE;
  INT_ARRAY NN_COUNT;
  INT_ARRAY FIX;

  REAL4_ARRAY T1;
  REAL4_ARRAY T2;
  REAL4_ARRAY T3;
  INT_ARRAY NN_IDS;
  REAL4_ARRAY FRICTION;

  INT PARTICLE_COUNT = 0;
  INT BOND_COUNT = 0;
  INT NN_MAX = 12;

  INT2_ARRAY BONDS;
  INT_ARRAY BOND_STATE;

  REAL8_ARRAY WALL_FORCES;

  REAL4_ARRAY FORCE_NORMAL;
  REAL4_ARRAY FORCE_TANGENTIAL;
  REAL4_ARRAY MOMENT_NORMAL;
  REAL4_ARRAY MOMENT_TANGENTIAL;

  INT_ARRAY BOND_TRANSFER_COUNT;
  INT_ARRAY BOND_TRANSFER_IDS;

};
